name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - name: Set environment variable
      run: | 
           echo "GITHUB_ACTION=true" >> $GITHUB_ENV
           echo "PUBLIC_NODE_ENV=development" >> $GITHUB_ENV
      shell: bash
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm config get cache)"
      shell: bash
    - uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
    - name: Install project dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash