export const REGION_NAME_CONSTANTS = {
	'us-east-2': 'US East (Ohio)',
	'us-east-1': 'US East (N. Virginia)',
	'us-west-1': 'US West (N. California)',
	'us-west-2': 'US West (Oregon)',
	'ca-central-1': 'Canada (Central)',
	'us-gov-west-1': 'AWS GovCloud (US-West)',
	'us-gov-east-1': 'AWS GovCloud (US-East)',
	'af-south-1': 'Africa (Cape Town)',
	'ap-east-1': 'Asia Pacific (Hong Kong)',
	'ap-south-2': 'Asia Pacific (Hyderabad)',
	'ap-southeast-3': 'Asia Pacific (Jakarta)',
	'ap-southeast-4': 'Asia Pacific (Melbourne)',
	'ap-south-1': 'Asia Pacific (Mumbai)',
	'ap-northeast-3': 'Asia Pacific (Osaka)',
	'ap-northeast-2': 'Asia Pacific (Seoul)',
	'ap-southeast-1': 'Asia Pacific (Singapore)',
	'ap-southeast-2': 'Asia Pacific (Sydney)',
	'ap-northeast-1': 'Asia Pacific (Tokyo)',
	'eu-central-1': 'Europe (Frankfurt)',
	'eu-west-1': 'Europe (Ireland)',
	'eu-west-2': 'Europe (London)',
	'eu-south-1': 'Europe (Milan)',
	'eu-west-3': 'Europe (Paris)',
	'eu-south-2': 'Europe (Spain)',
	'eu-north-1': 'Europe (Stockholm)',
	'eu-central-2': 'Europe (Zurich)',
	'me-south-1': 'Middle East (Bahrain)',
	'me-central-1': 'Middle East (UAE)',
	'sa-east-1': 'South America (Sao Paulo)',
	'us-east-1-phl-1': 'US East (Philadelphia)',
	'us-east-1-dfw-1': 'US East (Dallas)',
	'us-east-1-nyc-1': 'US East (New York City)',
	'us-west-2-sea-1': 'US West (Seattle)',
	'us-east-1-atl-1': 'US East (Atlanta)',
	'us-west-2-lax-1': 'US West (Los Angeles)',
	'us-west-2-den-1': 'US West (Denver)',
	'us-west-2-phx-1': 'US West (Phoenix)',
	'us-west-2-las-1': 'US West (Las Vegas)',
	'us-east-1-mia-1': 'US East (Miami)',
	'us-east-1-chi-1': 'US East (Chicago)',
	'us-east-1-msp-1': 'US East (Minneapolis)',
	'us-east-1-mci-1': 'US East (Kansas City 2)',
	'us-east-1-iah-1': 'US East (Houston)',
	'us-east-1-bos-1': 'US East (Boston)'
};
